development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  key:         1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

production:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  key:         1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict